### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by sielicki** [comment]
I have been unable to contribute to this flathub package for some time now; I do not have any personal desktop linux systems and am not even able to test contributions from others.

**Comment by AsciiWolf** [comment]
No worries, I also have push rights to this repository and I am testing the new build right now. :-)

**Review by sielicki — APPROVED** [review]

**Comment by AsciiWolf** [comment]
screenshot

The new build seems to work fine. :-)

**Comment by sielicki** [comment]
Nice nice nice, 73 de W9NLS.

**Pull request merged**
